### ISSUE TITLE
Referencing included aliases result in unidentified alias

### ISSUE THREAD

**Issue by johannes-z** [claylo/yaml-include#5]
Consider this file structure:

```yaml
# in include1.yml
props:
  - &key
    key: value
```

```yaml
# in main.yml
name: main

include1: !!inc/file include1.yml

properties:
  - *key
```

It will throw a YAMLException with: `unidentified alias "key"`, because the key isn't even included.
